# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Security.delete_all
secUser = Security.create([ role: "user", secret: "password"])
secUser = Security.create([ role: "admin", secret: "adminpassword"])

Fee.delete_all
fee = Fee.create([ from: "0", to: "10000", fee: "75.00"])
fee = Fee.create([ from: "10000", to: "30000", fee: "300.00"])
fee = Fee.create([ from: "30000", to: "50000", fee: "600.00"])
fee = Fee.create([ from: "50000", to: "70000", fee: "900.00"])
fee = Fee.create([ from: "70000", to: "90000", fee: "1200.00"])
fee = Fee.create([ from: "90000", to: "110000", fee: "1500.00"])
fee = Fee.create([ from: "110000", to: "130000", fee: "1800.00"])
fee = Fee.create([ from: "130000", to: "150000", fee: "2100.00"])
fee = Fee.create([ from: "150000", to: "175000", fee: "2450.00"])
fee = Fee.create([ from: "175000", to: "200000", fee: "2825.00"])
fee = Fee.create([ from: "200000", to: "225000", fee: "3200.00"])
fee = Fee.create([ from: "225000", to: "250000", fee: "3575.00"])
fee = Fee.create([ from: "250000", to: "275000", fee: "3950.00"])
fee = Fee.create([ from: "275000", to: "300000", fee: "4325.00"])
fee = Fee.create([ from: "300000", to: "325000", fee: "4700.00"])
fee = Fee.create([ from: "325000", to: "350000", fee: "5075.00"])
fee = Fee.create([ from: "350000", to: "375000", fee: "5450.00"])
fee = Fee.create([ from: "375000", to: "400000", fee: "5825.00"])
fee = Fee.create([ from: "400000", to: "425000", fee: "6200.00"])
fee = Fee.create([ from: "425000", to: "450000", fee: "6575.00"])
fee = Fee.create([ from: "450000", to: "475000", fee: "6950.00"])
fee = Fee.create([ from: "475000", to: "500100", fee: "7325.00"])

Clinic.delete_all
clinic = Clinic.create([ vendorid: "VN0003000", name: "Test Vendor VS", address: "Test ST, Oakville, ON"])
clinic = Clinic.create([ vendorid: "VN0003001", name: "Gall & Associates - Optometrists", address: "506 Kerr St., Oakville, ON"])
clinic = Clinic.create([ vendorid: "VN0003002", name: "St. Thomas Optometric Center", address: "208-230 First Avenue, St. Thomas, ON"])
clinic = Clinic.create([ vendorid: "VN0003003", name: "Vespa Vision Center", address: "Suite 102, 700 Tecumseh Road E, Windsor, ON"])
clinic = Clinic.create([ vendorid: "VN0003004", name: "Village Eyecare Optometry", address: "54 Wilson Street West, Unit 16, Ancaster, ON"])
clinic = Clinic.create([ vendorid: "VN0003005", name: "Manning Road Optometric Centre", address: "Suite 102, 700 Tecumseh Road E, Windsor, ON"])
clinic = Clinic.create([ vendorid: "VN0003006", name: "Van Ymeren & Townshend", address: "600 Colborne Street, London, ON"])
clinic = Clinic.create([ vendorid: "VN0003007", name: "Dr. Warren Samuel Optometry, P.C.", address: "2291 Kipling Avenue, Suite 119, Etobicoke, ON"])
clinic = Clinic.create([ vendorid: "VN0003008", name: "Dr. Valerie Dippel", address: "77 Water Street North, Kitchener, ON"])
clinic = Clinic.create([ vendorid: "VN0003009", name: "Dr. Dawn Clarke", address: "77 Water Street North, Kitchener, ON"])
clinic = Clinic.create([ vendorid: "VN0003010", name: "Eyes On Sheppard", address: "180 Sheppard Ave. East, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003011", name: "Dr. Pavan Avinashi Optometric Corp.", address: "61 Lonsdale Ave., North Vancouver, BC"])
clinic = Clinic.create([ vendorid: "VN0003012", name: "Dr. Pavan Avinashi, Optometric Corp.", address: "61 Lonsdale Ave., BC, V7M2E5, North Vancouver, BC"])
clinic = Clinic.create([ vendorid: "VN0003014", name: "Dr. Jason Morris Optometry, P.C.", address: "208 - 230 First Avenue, St. Thomas, ON"])
clinic = Clinic.create([ vendorid: "VN0003015", name: "Jason Holtom, Professional Corp. & Tedra Kindopp, Profession", address: "East Hill Centre 510-3020 22 St., Red Deer, AB"])
clinic = Clinic.create([ vendorid: "VN0003016", name: "Dr. Neel Vyas, Optometry, P.C.", address: "822 St. Clair Ave. W, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003017", name: "Dr. Michael Kaplan Optometry, Professional Corporation", address: "5 Fairview Mall Drive, Ste. 110, North York, ON"])
clinic = Clinic.create([ vendorid: "VN0003018", name: "Markham Optometric Clinic", address: "4997 Highway 7, Unit 110, Markham, ON"])
clinic = Clinic.create([ vendorid: "VN0003019", name: "Opticon", address: "1409-77 Bloor St. West, Ste. 1409, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003020", name: "Dr. D. Thornborrow, Optometry, P.C.", address: "P.O. Box 1025, Waterdown, ON"])
clinic = Clinic.create([ vendorid: "VN0003021", name: "Dr. M. Richmond, Optometry, P.C.", address: "P.O. Box 1025, Waterdown, ON"])
clinic = Clinic.create([ vendorid: "VN0003022", name: "Waterdown Optometric Clinic", address: "P.O. Box 1025, Waterdown, ON"])
clinic = Clinic.create([ vendorid: "VN0003023", name: "Jason Morris Optometry, P.C.", address: "208 - 230 First Avenue, St. Thomas, ON"])
clinic = Clinic.create([ vendorid: "VN0003024", name: "Kevin J. Tyber, O.D.", address: "556 Kingston Rd. West, Ajax, ON"])
clinic = Clinic.create([ vendorid: "VN0003025", name: "Manbir Randhawa, O.D.", address: "2625 East 49th Ave, Vancouver, BC"])
clinic = Clinic.create([ vendorid: "VN0003026", name: "Dr. Mimmo Gagliardi, Optometrist", address: "8633 Weston Road, Unit 10, Woodbridge, ON"])
clinic = Clinic.create([ vendorid: "VN0003027", name: "Dr. Mimmo Gagliardi, Optometrist", address: "2100 Finch Ave. West, Ste. 102, North York, ON"])
clinic = Clinic.create([ vendorid: "VN0003028", name: "Timothy Kiddie, O.D.", address: "4085 Hamilton Road, Dorchester, ON"])
clinic = Clinic.create([ vendorid: "VN0003029", name: "Dr. Shalu Pal Optometry Professional Corporation", address: "94 Cumberland St., Ste. 902, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003030", name: "Drs. Bauman& Schropp- DBA Old South Optometry", address: "393 Wharncliffe Rd. S, London, ON"])
clinic = Clinic.create([ vendorid: "VN0003032", name: "Dr. Jarrett & Associates", address: "200 University Ave., Ste. 100, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003033", name: "Dr. Sameen Chatoo and Associates", address: "2175 Sheppard Ave., East, Suite 206, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003034", name: "Kevin Ahokas Optometry Professional Corporation", address: "535 Upper Wellington St., Hamilton, ON"])
clinic = Clinic.create([ vendorid: "VN0003036", name: "Drs. Chung & Tse, Optometrists", address: "318 Broadview Ave., Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003037", name: "Jo-Anne Monteiro & Associates, Optometrists", address: "1960 Appleby Line, Suite 12, Burlington, ON"])
clinic = Clinic.create([ vendorid: "VN0003038", name: "1754554 Ontario Limited - Dr. Harvey Mayers", address: "3300 Bloor St. West, Ste 2260, Centre Tower, Etobicoke, ON"])
clinic = Clinic.create([ vendorid: "VN0003040", name: "Francis Dube, O.D.", address: "1264 Garrison Rd., Unit 4, Fort Erie, ON"])
clinic = Clinic.create([ vendorid: "VN0003041", name: "Innisfil Eye Care", address: "7975 Yonge St., Unit 14, Innisfil, ON"])
clinic = Clinic.create([ vendorid: "VN0003042", name: "Dr. Jason Hershorn - St. Clair Optometry", address: "1366 Yonge St., Ste. 103, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003043", name: "Waverley Eye Care Centre, Inc.", address: "1-1200 Waverly St., Winnipeg, MB"])
clinic = Clinic.create([ vendorid: "VN0003044", name: "Yorkview Optometric Clinic", address: "480 Smith St., Arthur, ON"])
clinic = Clinic.create([ vendorid: "VN0003045", name: "Dr. Robert D. Gole B.Sc.,O.D - Yorkview Optometric Clinic", address: "480 Smith St., Arthur, ON"])
clinic = Clinic.create([ vendorid: "VN0003046", name: "Finch Avenue Optometry & Low Vision Clinic", address: "244 Finch Ave., W, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003047", name: "Thornhill Optometric Centre", address: "11 disera Dr., Unit 150, Thornhill, ON"])
clinic = Clinic.create([ vendorid: "VN0003048", name: "Vi Tu Banh Optometry, Professional Corporation", address: "2 Elgin Park Dr., Unit D, Uxbridge, ON"])
clinic = Clinic.create([ vendorid: "VN0003049", name: "Dr. Gary Kogon", address: "2  Robert  Speck  Parkway,  Suite   150, Mississauga, ON"])
clinic = Clinic.create([ vendorid: "VN0003050", name: "Yih Ling Chang Optometry, P.C.", address: "62 Ellesmere Rd., Scarborough, ON"])
clinic = Clinic.create([ vendorid: "VN0003051", name: "Lowy Optometry Professional Corporation", address: "1520 Steeles Ave., W., Ste 120 - A, Concord, ON"])
clinic = Clinic.create([ vendorid: "VN0003052", name: "Dr. T.W. Chalaturnyk & Associates", address: "679 Davis Dr., Unit 321, Newmarket, ON"])
clinic = Clinic.create([ vendorid: "VN0003053", name: "Urban Optik, Ltd.", address: "18328 Lessard Rd., Edmonton, AB"])
clinic = Clinic.create([ vendorid: "VN0003054", name: "I Sight Optometry", address: "#4-2070 Harvey Ave., Kelowna, BC"])
clinic = Clinic.create([ vendorid: "VN0003055", name: "Gregory V. Wong, O.D.", address: "50 - 8 Glen Warford Dr., Scarborough, ON"])
clinic = Clinic.create([ vendorid: "VN0003056", name: "T.L. Brodie Optometry Professional Corp.", address: "405 Pearl St., Burlington, ON"])
clinic = Clinic.create([ vendorid: "VN0003057", name: "Dr. Gary Nelles Optometry Professional Corporation", address: "36 Brock St. West, Tillsonburg, ON"])
clinic = Clinic.create([ vendorid: "VN0003058", name: "Precision Eye Care", address: "2965 Ellwood Dr., Edmonton, AB"])
clinic = Clinic.create([ vendorid: "VN0003059", name: "BIlli Jayne Prinzen, O.D.", address: "13380 Loyalist Parkway, Picton, ON"])
clinic = Clinic.create([ vendorid: "VN0003060", name: "Dr.'s Hall, Ritchie & Smith", address: "51 Water St. North, Cambridge, ON"])
clinic = Clinic.create([ vendorid: "VN0003061", name: "Dr.'s Hall, Ritchie & Smith", address: "51 Water St. North, Cambridge, ON"])
clinic = Clinic.create([ vendorid: "VN0003062", name: "Dr.'s Hall, Ritchie & Smith", address: "51 Water St. North, Cambridge, ON"])
clinic = Clinic.create([ vendorid: "VN0003063", name: "Optometry on Hyde Park", address: "19 Tanglewood Ave., London, ON"])
clinic = Clinic.create([ vendorid: "VN0003066", name: "Dr. Mark Yoshimura, Yorkview Vision & Eyecare", address: "3695 Keele St., Ste. 101, Downsview, ON"])
clinic = Clinic.create([ vendorid: "VN0003067", name: "Orangeville Optometrists", address: "31 First St., Orangeville, ON"])
clinic = Clinic.create([ vendorid: "VN0003068", name: "Mainstreet Optometric", address: "P.O. Box 189, Bayfield, ON"])
clinic = Clinic.create([ vendorid: "VN0003069", name: "Dr. Shahreena Rahman", address: "261 Talbot St. West, Aylmer, ON"])
clinic = Clinic.create([ vendorid: "VN0003070", name: "Dr. Murray McLeod - DBA Sunningdale Optometry", address: "45 Kingspark Cres, London, ON"])
clinic = Clinic.create([ vendorid: "VN0003071", name: "James Allan Maki, O.D.", address: "2380 Long Lake Rd., Sudbury, ON"])
clinic = Clinic.create([ vendorid: "VN0003074", name: "Dr. Angela Yoon, Optometry Professional Corporation", address: "3030 Lawrence Avenue East, Ste. 106, Scarborough, ON"])
clinic = Clinic.create([ vendorid: "VN0003075", name: "Dr. Linda Voisin Optometry, Profesional Corporation", address: "4997 Highway 7, Unit 110, Markham, ON"])
clinic = Clinic.create([ vendorid: "VN0003076", name: "Dr. M. Moussa Optometry Professional Corporation", address: "2682 Tecumseh Rd. E, Windsor, ON"])
clinic = Clinic.create([ vendorid: "VN0003077", name: "Hans C. Schuster, O.D.", address: "22 Market Street South, Brantford, ON"])
clinic = Clinic.create([ vendorid: "VN0003078", name: "Angela Morley, O.D., P.C.", address: "#1-530 Saint Albert Trail, Saint Albert, AB"])
clinic = Clinic.create([ vendorid: "VN0003079", name: "Shuit Optometry Professional Corporation", address: "640 Wellington St., London, ON"])
clinic = Clinic.create([ vendorid: "VN0003080", name: "Dr. Shailinder Bhullar", address: "101-12827 76 Ave., Surrey, BC"])
clinic = Clinic.create([ vendorid: "VN0003081", name: "Dr. Peter Rozanec, Optometric Professional Corporation", address: "228 Lakeshore Rd. W, Ste. 6, Mississauga,, ON"])
clinic = Clinic.create([ vendorid: "VN0003082", name: "Dr. Anthony DiPasquale", address: "80 Richmond St., Amherstburg, ON"])
clinic = Clinic.create([ vendorid: "VN0003083", name: "Dr. Daniel Rayman Optometry Professional Corporation", address: "9-372 Tower Hill Rd., Richmond Hill, ON"])
clinic = Clinic.create([ vendorid: "VN0003084", name: "Amany Wissa, Professional Optometric Incoporation", address: "110 Brickyard Way, Brampton, ON"])
clinic = Clinic.create([ vendorid: "VN0003085", name: "Dr. Shanthy Sandrasekaramudaly Brown", address: "3351 Markham Rd., Unit A125, Scarborough, ON"])
clinic = Clinic.create([ vendorid: "VN0003086", name: "Shea Colpitts, O.D.", address: "213-4368 Main St., Whistler, BC"])
clinic = Clinic.create([ vendorid: "VN0003087", name: "Drs. A Y.C. Wong, C. Shum, J.C. Ng, Optometric Corporation", address: "4657 Lougheed Highway Unit 51, Burnaby, BC"])
clinic = Clinic.create([ vendorid: "VN0003088", name: "Drs. Anthony Y.C. Wong and Cindy Shum, Optometric Corporatio", address: "B-369 Dollarton Highway North, North Vancouver, BC"])
clinic = Clinic.create([ vendorid: "VN0003089", name: "2098446 Ontario Ltd.", address: "Suite 102, 700 Tecumseh Road E, Windsor, ON"])
clinic = Clinic.create([ vendorid: "VN0003090", name: "Dr. Pavan Avinashi, Optometric Corporation", address: "301 E. Columbia St., Ste. 108-301, New Westminster, BC"])
clinic = Clinic.create([ vendorid: "VN0003091", name: "Dr. Daniel Rayman Optometry Professional Corporation", address: "23 King St. W., Box 604, Bolton, ON"])
clinic = Clinic.create([ vendorid: "VN0003092", name: "Dr. Daniel Do Optometry P.C.  DBA:  Kingsway Eye Care Family", address: "41 Thompson Ave., Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003093", name: "Dr. Vernon Prentice Optometry Professional Corporation", address: "481 MacKay St., Pembroke, ON"])
clinic = Clinic.create([ vendorid: "VN0003094", name: "Dianne Powell, O.D.", address: "20 Kingsbridge Garden circle, Ste. 2002, Mississauga, ON"])
clinic = Clinic.create([ vendorid: "VN0003095", name: "Vs.eye.Optometry, Inc.", address: "102-18640 Fraser Hwy., Surrey, BC"])
clinic = Clinic.create([ vendorid: "VN0003096", name: "Dr. Chris Schell Optometry Professional Corporation", address: "225 Ferndale Drive South, Unit 6, Barrie, ON"])
clinic = Clinic.create([ vendorid: "VN0003097", name: "Dre D. Frigault Optometrie Societe Professionnelle", address: "1624 Laurier St., Clarence-Rockland, ON"])
clinic = Clinic.create([ vendorid: "VN0003098", name: "Alyssa E. Markowitz, Optometry Professional Corporation", address: "Unit 3, 1209 King St. W, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003099", name: "Alyssa E. Markowitz, Optometry Professional Corporation", address: "1209 King St. W, Unit 3, Toronto, ON"])
clinic = Clinic.create([ vendorid: "VN0003100", name: "Laurin Optometry Professional Corporation", address: "2828 St. Joseph Blvd., Orleans, ON"])
clinic = Clinic.create([ vendorid: "VN0003101", name: "Laurin Optometry Professional Corporation", address: "2828 St. Joseph Blvd., Orleans, ON"])
clinic = Clinic.create([ vendorid: "VN0003102", name: "Brian C. Blake, O.D.", address: "2629 Howard Ave, Unit B Devon Plaza, Windsor, ON"])
clinic = Clinic.create([ vendorid: "VN0003103", name: "Chong-hwa Michael Shin, O.D.", address: "138 - 7181 Yonge St., Thornhill, ON"])
clinic = Clinic.create([ vendorid: "VN0003104", name: "Pickering Optometric Clinic DBA: Oshawa Optometric Centre", address: "212-1885 Glenanna Road, Pickering, ON"])
clinic = Clinic.create([ vendorid: "VN0003105", name: "Pickering Optometric Clinic  DBA:  Pickering Optometric Clin", address: "212-1885 Glenanna Road, Pickering, ON"])

MembershipFee.delete_all